In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('StudentData.csv')
df

    Age  Gender Department  StudyHours  Marks
0    18    Male    Science         3.0   65.0
1    19  Female   Commerce         4.0   70.0
2    20    Male       Arts         2.0   60.0
3    21  Female    Science         5.0   75.0
4    22    Male   Commerce         NaN   68.0
5    23  Female       Arts         3.0   72.0
6    24    Male    Science         4.0   78.0
7    25  Female   Commerce         5.0   80.0
8    26    Male       Arts         NaN   62.0
9    27  Female    Science         4.0   85.0
10   28    Male   Commerce         6.0   88.0
11   29  Female       Arts         3.0   70.0
12   30    Male    Science         5.0   90.0
13   21  Female   Commerce         2.0   66.0
14   22    Male       Arts         4.0    NaN
15   23  Female    Science         3.0   74.0
16   24    Male   Commerce         5.0   82.0
17   25  Female       Arts         4.0   76.0
18   26    Male    Science         NaN   84.0
19   27  Female   Commerce         6.0   88.0

In [4]:
df.shape

(20, 5)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         20 non-null     int64
 1   Gender      20 non-null     object
 2   Department  20 non-null     object
 3   StudyHours  17 non-null     float64
 4   Marks       19 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 932.0+ bytes

In [6]:
df.isnull().sum()

Age           0
Gender        0
Department    0
StudyHours    3
Marks         1
dtype: int64

Handling Missing Values

(a)Mean Imputation (StudyHours)

In [19]:
print(df['StudyHours'].mean())
df['StudyHours'] = df['StudyHours'].fillna(df['StudyHours'].mean())

1.1102230246251566e-17

(b) Median Imputation (Marks)

In [20]:
print(df['Marks'].median())
df['Marks'] = df['Marks'].fillna(df['Marks'].median())

-0.04605312990585032

(c) Mode Imputation (if needed – categorical)

In [ ]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

0

(d) IQR Method (Outlier Detection – Marks)

In [17]:
Q1 = df['Marks'].quantile(0.25)
Q3 = df['Marks'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Cap outliers
df['Marks'] = np.where(df['Marks'] < lower, lower,
                        np.where(df['Marks'] > upper, upper, df['Marks']))
df['Marks']

0    -1.197381
1    -0.621717
2    -1.773046
3    -0.046053
4    -0.851983
5    -0.391452
6     0.299345
7     0.529611
8    -1.542780
9     1.105275
10    1.450674
11   -0.621717
12    1.680939
13   -1.082249
14   -0.046053
15   -0.161186
16    0.759877
17    0.069080
18    0.990142
19    1.450674
Name: Marks, dtype: float64

e)Standard deviation

In [11]:
df['Marks'].std()

np.float64(8.911258402481069)

Label Encoding (Gender)

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

print(df[['Gender']].head())

   Gender
0       1
1       0
2       1
3       0
4       1

Dummy Variables (Department)

In [13]:
df = pd.get_dummies(df, columns=['Department'], drop_first=True)

print(df.head())

   Age  Gender  StudyHours  Marks  Department_Commerce  Department_Science
0   18       1         3.0   65.0                False                True
1   19       0         4.0   70.0                 True               False
2   20       1         2.0   60.0                False               False
3   21       0         5.0   75.0                False                True
4   22       1         4.0   68.0                 True               False

Normalization (Min-Max Scaling)

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[['Age', 'StudyHours', 'Marks']] = scaler.fit_transform(
    df[['Age', 'StudyHours', 'Marks']]
)

print(df.head())

        Age  Gender  StudyHours     Marks  Department_Commerce  \
0  0.000000       1        0.25  0.166667                False
1  0.083333       0        0.50  0.333333                 True
2  0.166667       1        0.00  0.000000                False
3  0.250000       0        0.75  0.500000                False
4  0.333333       1        0.50  0.266667                 True

   Department_Science
0                True
1               False
2               False
3                True
4               False

Scaling (Standardization)

In [15]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

df[['Age', 'StudyHours', 'Marks']] = std_scaler.fit_transform(
    df[['Age', 'StudyHours', 'Marks']]
)

print(df.head())

        Age  Gender  StudyHours     Marks  Department_Commerce  \
0 -1.851640       1   -0.912871 -1.197381                False
1 -1.543033       0    0.000000 -0.621717                 True
2 -1.234427       1   -1.825742 -1.773046                False
3 -0.925820       0    0.912871 -0.046053                False
4 -0.617213       1    0.000000 -0.851983                 True

   Department_Science
0                True
1               False
2               False
3                True
4               False

Final Preprocessed Dataset

In [16]:
df.head()

,Age,Gender,StudyHours,Marks,Department_Commerce,Department_Science
0,-1.851640,1,-0.912871,-1.197381,False,True
1,-1.543033,0,0.000000,-0.621717,True,False
2,-1.234427,1,-1.825742,-1.773046,False,False
3,-0.925820,0,0.912871,-0.046053,False,True
4,-0.617213,1,0.000000,-0.851983,True,False